<?php
/* Copyrights Mai 213, MAGHEN NEGOU Rostant, Tout droit réservé
MAGHEN NEGOU Rostant
Communicateur Informaticien
Tél:(+237) 77 92 06 85 - 94 27 12 80 - 77 55 57 43 - 77 28 28 51
BP: Douala Cameroun
Email : maghen2@gmail.com
*/
$_article=array(
'title'=>'Mon Portfolio et Mes Références Professionnelles',
  'keyword'=>'Portfolio, Références Professionnelles, réalisations, Preuves',
  'description'=>'Au cours de ma carrière professionnelle, j\'ai eu à diriger la Conception, la Réalisation et la Maintenance de nombreux sites web. Je vous propose une liste non exhaustive de quelques uns des sites web que j\'ai eu à faire seule ou en équipe. Mais n\'oubliez pas que chaque projet est unique et que seule une étude approfondie de votre projet, de vos envies et de vos spécificités me permetra de vous proposer une solution adaptée. N\'hésitez pas à me contacter afin que nous commencions par le commencement: Déterminer vos besoins.',
  'date'=>'général',
  'categorie'=>'2013-04-18 16:44:29',
  'genre'=>'references',
  'content'=>'<h1>MON PORTFOLIO, MES RÉFÉRENCES</h1><p>Au cours de ma carrière professionnelle,<strong> j\'ai eu à diriger la Conception, la Réalisation et la Maintenance de nombreux sites web.</strong> Je vous propose une<strong> liste non exhaustive de quelques uns des sites web que j\'ai eu à faire </strong>seule ou en équipe. Mais n\'oubliez pas que<strong> chaque projet est unique </strong>et que seule une étude approfondie de votre projet, de vos envies et de vos spécificités me permetra de vous proposer une solution adaptée.</p> <a href="contact.php"  title="Contact de MAGHEN NEGOU Rostant, Communicateur et Informaticien à Douala au Cameroun"><strong> N\'hésitez pas à me contacter afin que nous commencions par le commencement: Déterminer vos besoins.</strong></a><h1 style="font-variant: small-caps"> Quelques unes de mes réalisations</h1><h2> <a href="http://www.afriqueplus.net/1.html">AFRIQUEPLUS.NET</a></h2><div> <a href="http://www.afriqueplus.net/1.html" title="AFRIQUEPLUS.NET">
<img border="0" width="250" height="227" src="src/img/portfolio/afriqueplus.net.jpg" alt="AFRIQUEPLUS.NET" ></a><p>&laquo;Rester debout, au nom de la modeste cause que nous prétendons servir. Notre petite histoire pouvait difficilement être plus joyeuse que celle de l’Afrique elle-même. Mais nous n’oublions pas que sur ce continent, il y a aussi des réussites, qui sont le fruit d’un long travail, de la détermination, d’une certaine abnégation, et même de la souffrance, souvent...&raquo; <a href="contact.php"><strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas à me contacter.</strong></a></p></div><h2> <a href="http://blog.afriqueplus.net/">BLOG AFRIQUEPLUS.NET</a></h2><div> <a href="http://blog.afriqueplus.net/" title="BLOG AFRIQUEPLUS.NET"> <img border="0" width="250" height="227" src="src/img/portfolio/blog.afriqueplus.net.jpg" alt="BLOG AFRIQUEPLUS.NET"></a>
<p>&laquo;D\'après vous croyez-vous que le départ ou la présence de Robert Mugabé comme président du Zimbabwé est compatible ou incompatible avec la fin des Sanctions Économiques des Pays Occidentaux, du FMI, et de la Banque Mondiale ? Selon vous le Zimbabwé s’en sortira-t-il sans cette levée de sanctions Économiques ?Quelle rôle doit jouer l\'opposition Zimbabwénne? Comment l\'Afrique peut-elle aider le Zimbabwé ?...&raquo; <a href="contact.php"><strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas à me contacter.</strong></a></p></div><h2> <a href="/">MON SITE PERSO</a></h2><div> <a href="/" title="MON SITE PERSO"> <img border="0" width="303" height="227" src="src/img/portfolio/maghen.org.jpg" alt="MON SITE PERSO" ></a><p>&laquo;<strong><i>Relever de nouveaux défits est ma Passion, Jouir du travail bien-fait est ma Motivation, Travailler avec vous sera un Plaisir.</i></strong></p>
<p> Je me propose de vous <strong>offrir un accompagnement personnalisé, dans la réalisation de vos différents projets,</strong> que ce soit en Communication (<strong>communication institutionnelle</strong>, <strong>communication événementielle</strong>, <strong>communication interne</strong>, <strong>relations de presse et relations publiques</strong>) ou en informatique (<strong>Programmation Web</strong> et <strong>Programmation Desktop</strong>)....&raquo; <a href="contact.php"><strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas à me contacter.</strong></a></p></div><h1 style="font-variant: small-caps"> Quelques un de mes travaux en cours</h1><h2> <a href="#">CABLE PRO 1.0</a></h2><div> <a href="#" title="CABLE PRO 1.0"> <img border="0" width="250" src="src/img/portfolio/cable_pro.jpg" alt="CABLE PRO 1.0" ></a>
<p><strong>CABLE PRO est un progiciel de gestion spécialisé dans la gestion des PME de cablo-distribution.</strong> Il a pour objectif d\'<strong>optimiser  la gestion des PME de cablo-distribution tout en facilitant au maximum l’exécution des taches</strong> de gestion. Il puise sa puissance sur une <strong>analyse critique des logiciels semblables</strong> qui existent déjà sur le marché tout en empreintant les qualités des progiciels édités par les grandes firmes mondiales. <strong>Sa conception est le fruit d\'une étroite collaboration avec les utilisateurs finaux</strong>. Les fonctions du logiciels sont en cours d\'implémentation. La première version stable devrait être finalisée d\'ici la fin d\'année. <a href="contact.php"><strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas à me contacter.</strong></a></p></div><h2> <a href="http://douala-shopping.cm">DOUALA SHOPPING</a></h2><div> <a href="http://douala-shopping.cm" title="DOUALA SHOPPING">
<img border="0" width="250" src="src/img/portfolio/douala_shopping.jpg" alt="DOUALA SHOPPING" ></a><p><strong>DOUALA SHOPPING est un site d\' e-commerce camerounais.</strong> Il fait dans la vente en ligne de matériels informatiques, électroniques et téléphoniques. Il a pour but d’élargir la clientèle traditionnelle de l\'enseigne en attirants des e-acheteurs. Ce site est propulsé par une multi-intégration de <strong>trois CMS différents : WordPress, OsCommerce et PrestaShop.</strong> Certaines fonctionnalités telles que le <strong>design, la régionalisation et l’intégration automatique de la base de donné du site web avec celui de la boutique physique</strong>;  ont été totalement reprogrammées. <a href="contact.php"><strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas à me contacter.</strong></a></p></div><h2> <a href="http://raphainc-sarl.com">RAPHA INC Sarl</a></h2><div> <a href="http://raphainc-sarl.com" title="RAPHA INC Sarl">
<img border="0" width="250" src="src/img/portfolio/rapha_inc_sarl.jpg" alt="RAPHA INC Sarl" ></a><p> Située en Afrique Centrale et basée dans la ville de Douala au Cameroun, <strong>RAPHA INC Sarl</strong> a été fondée en Décembre 1999 par Madame <strong>DANKAM Chandra</strong>, gérante de la dite Entreprise. <strong>RAPHA INC Sarl</strong> exerce dans des secteurs d\'activité divers dont les principaux sont <strong>la menuiserie bois, l’agriculture, la fourniture des bambous et rotins</p><p>Ayant acquis une <strong>solide expérience professionnelle dans le domaine du bois grâce aux 20 années</strong> passées dans l\'exploitation des essences forestières et la menuiserie bois, le Directeur Technique, <strong>Mr KAMGANG ROBINSON</strong> est le promoteur du projet d\'exploitation des énergies renouvelables dont il pilote <strong>la production, le contrôle qualité et la logistique des matériaux renouvelables, des biocarburants et de la biomasse</strong>.
<a href="contact.php"><strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas à me contacter.</strong></a></p></div><h2> <a href="http://www.ocampeassur.com">OCAMPE ASSUR Sarl</a></h2><div> <a href="http://www.ocampeassur.com" title="OCAMPE ASSUR Sarl"> <img border="0" width="250" src="src/img/portfolio/ocampe_assur.jpg" alt="OCAMPE ASSUR Sarl" ></a><p><strong>OCAMPE ASSUR Sarl</strong>  a reçu l&#8217;agrément du Ministère des Transports pour la mise en place du Projet de rationalisation et de sécurisation du transport urbain par taxi par un système de geolocalisation et d&#8217;alerte à travers des chapeaux électroniques d&#8217;identification, que consacre l&#8217;Arrêté n° 000034/A/MINT du 24 février 2012 du Ministre des transports, qui par ailleurs le rend obligatoire.            <a href="contact.php"><strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas à me contacter.</strong></a></p></div>'
  );
?>
