<?php
/* Copyrights Mai 213, MAGHEN NEGOU Rostant, Tout droit réservé
MAGHEN NEGOU Rostant
Communicateur Informaticien
Tél:(+237) 77 92 06 85 - 94 27 12 80 - 77 55 57 43 - 77 28 28 51
BP: Douala Cameroun
Email : maghen2@gmail.com
*/
$_article=array(
'title'=>'Ma Formation et Ma Vie Professionnelle',
  'keyword'=>' CV, Curriculum Vitae, Lettre de Motivation, Demande d\'emploi',
  'description'=>' Formé en communication des entreprises et des organisations, également formé en Conception-réalisation de sites web et en Génie logiciel, fort de mon expérience professionnel riche et varié, je suis parfaitement outillé de part mes différentes formations agrémentées de mes expériences professionnelles, à apporter un gain de productivité certain à votre entreprise. MAGHEN NEGOU Rostant',
  'date'=>'général',
  'categorie'=>'2013-04-18 16:44:29',
  'genre'=>' cv',
  'content'=>'<h1>Ma Formation et Ma Vie Professionelle</h1><h2>EN RÉSUMÉ</h2><p>Form&eacute; en <strong>communication des entreprises et des organisations</strong>, &eacute;galement form&eacute; en <strong>Conception-r&eacute;alisation de sites web</strong> et en <strong>G&eacute;nie logiciel</strong>, fort de mon exp&eacute;rience professionnel riche et vari&eacute;, je suis parfaitement outill&eacute; de part mes diff&eacute;rentes formations agr&eacute;ment&eacute;es de ma longue exp&eacute;rience professionnelle, <strong>&agrave; apporter un gain de productivit&eacute; certain &agrave; votre entreprise</strong>.
&nbsp;&nbsp;<strong>Pour en savoir plus, n\'hésitez pas <a href="publications.php#lettre_de_motivation_maghen_negou_rostant"  title="Lettre de Motivation de MAGHEN NEGOU Rostant, COMMUNICATEUR INFORMATICIEN (10 ans d’expérience)"> à consulter ma Lettre de Motivation</a> ou alors <a href="contact.php" title="Contact de MAGHEN NEGOU Rostant, Communicateur et Informaticien à Douala au Cameroun"> à me contacter directement.</a></strong></p><p>Je me propose de vous <strong>offrir un accompagnement personnalis&eacute;, dans la r&eacute;alisation de vos diff&eacute;rents projets,</strong> que ce soit en <strong>Communication</strong>, en <strong>Marketing</strong> ou en <strong>Programmation Informatique.</strong>
&nbsp;&nbsp;<strong>Pour en savoir plus, n\'hésitez pas <a href="publications.php#offre_de_services_en_communication_marketing_et_creation_de_sites_web" title="J\'offre un service complet qui couvre les domaines du Marketing, de la Communication et de la Programmation Informatique. 10 années d’expérience professionnelle dans ces domaines m\'ont permis une excellente maîtrise des outils d\'élaboration et d’implémentation de solutions efficaces.  Ainsi ma formation pluridisciplinaire répond aux exigences des différents postes que j\'ai eu à occuper dans divers entreprises. Ce ci m\'a amené à me spécialisé en Communication Marketing Intégrée (CMI). Ma mission est de collaborer avec une variété de clients et une équipe d\'employés motivés et responsables, afin d\'offrir des solutions innovatrices, en ayant toujours en tête l\'obligation de résultats. En effet, Au cours de ma carrière, j\'ai tout particulièrement mis l\'accent sur l\'amélioration des procédés internes et l\'augmentation du chiffre d\'affaires. Comme vous pourrez le constater à la lecture de mon CV, je suis un habitué des univers dynamiques et exigeants. je recherche aujourd’hui de nouveaux défis à relever dans lesquelles je pourrais mettre à profit aussi bien mon  expérience que mes qualités relationnelles. Je me tiens à votre disposition pour toute information complémentaire"> à consulter mon Offre de services en communication-marketing et création de sites web</a> ou alors <a href="contact.php" title="Contact de MAGHEN NEGOU Rostant, Communicateur et Informaticien à Douala au Cameroun"> à me contacter directement.</a></strong></p>
<h2>MES COMPÉTENCES</h2><h3>COMPÉTENCES EN INFORMATIQUE</h3><ul> <li><b>PROGRAMMATION: JAVA, PHP, MySQL, JavaScript, XHTML, et CSS</b></li> <li><b>WEBMASTERING: Conception, réalisation et Maintenance  de sites web</b></li> <li><b>BUREAUTIQUE: Maîtrise les progiciels Microsoft Office et Libre Office</b></li></ul><h3>COMPÉTENCES EN COMMUNICATION</h3><ul> <li><b>communication événementielle</b></li> <li><b>communication institutionnelle</b></li> <li><b>communication interne</b></li> <li><b>image de marque</b></li> <li><b>journal interne</b></li> <li><b>promotion</b></li> <li><b>publicité</b></li> <li><b>rédaction de contenu</b></li> <li><b>relations de presse</b></li> <li><b>relations publiques</b></li> <li><b>sponsoring</b></li></ul><h3>COMPÉTENCES EN MARKETING</h3>
<ul><li><b>étude de marché</b></li> <li><b>stratégie marketing</b></li> <li><b>marketing mix</b></li> <li><b>marketing internet</b></li> <li><b>plan marketing</b></li> <li><b>étude du consommateur</b></li> <li><b>étude comportemental</b></li> <li><b>business plan</b></li> <li><b>Analyse SWOT</b></li> <li><b>analyse de la concurrence</b></li> <li><b>Axes de positionnement</b></li></ul><h3>COMPÉTENCES EN VIDÉOLUDIQUE </h3><p> <b>Installation, programmation et configuration des consoles de jeux et bornes arcades</b></p><p>&nbsp;&nbsp;<strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas <a href="publications.php#cv_maghen_negou_rostant"  title="CV de MAGHEN NEGOU Rostant, COMMUNICATEUR INFORMATICIEN (10 ans d’expérience)"> à consulter mon CV</a> ou alors <a href="contact.php" title="Contact de MAGHEN NEGOU Rostant, Communicateur et Informaticien à Douala au Cameroun"> à me contacter directement.</a></strong></p><h2>MES FORMATIONS ET MES DIPLÔMES</h2><ul>
<li><b>FORMATION PRÉ-EMPLOI EN MARKETING: 6 Mois de formation théorique et pratique en marketing (prospection vente)</b></li> <li><b>BACCALAURÉAT de l\'Enseignement Secondaire Général série  &laquo; C  &raquo; (Mathématiques et Physique)</b></li> <li><b>FORMATION PROFESSIONNELLE en Conception, Développement et Maintenance de Site Web (Programmation Web)</b></li> <li><b>LICENCE en Communication des Entreprises et des Organisations (Université de Douala)</b></li> <li><b>FORMATION PROFESSIONNELLE en Génie Logiciel option programmation en JAVA (Programmation Desktop)</b></li></ul><p>&nbsp;&nbsp;<strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas <a href="publications.php#cv_maghen_negou_rostant"  title="CV de MAGHEN NEGOU Rostant, COMMUNICATEUR INFORMATICIEN (10 ans d’expérience)"> à consulter mon CV</a> ou alors <a href="contact.php" title="Contact de MAGHEN NEGOU Rostant, Communicateur et Informaticien à Douala au Cameroun"> à me contacter directement.</a></strong></p>
<h2>MES EXPÉRIENCES PROFESSIONNELLES</h2><h3>MES EXPÉRIENCES PROFESSIONNELLES EN COMMUNICATION-MARKETING</h3><p> J\'ai débuté ma vie professionnelle par une formation-emploi pour un poste d\'<strong>agent commercial dans une compagnie d\'assurance</strong> de la ville de Douala. Nous nous rendions dans les zones de fortes affluences d\'engins motorisés(Gares routières, Stations services, Parc automobiles, etc) afin de convaincre des prospects de souscrire leurs polices d\'assurances dans notre compagnie.</p><p> J\'ai ensuite travaillé, tout d\'abord comme <strong>agent commercial</strong>, puis comme <strong>responsable de la distribution</strong> chez un producteur d\'huile de palmiste raffinée. J\'ai également occupé un <strong>poste similaire</strong> chez un distributeur de produits vestimentaire.
</p>Depuis 2010, je suis Consultant en <strong>Communication Marketing Intégrée</strong> dans  une société de création vidéoludique. Je les aides à faire la maintenance et le management des points de vente vidéoludiques et d\'une boutique de vente de téléphone.<p></p><p>&nbsp;&nbsp;<strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas <a href="publications.php#cv_maghen_negou_rostant"  title="CV de MAGHEN NEGOU Rostant, COMMUNICATEUR INFORMATICIEN (10 ans d’expérience)"> à consulter mon CV</a> ou alors <a href="contact.php" title="Contact de MAGHEN NEGOU Rostant, Communicateur et Informaticien à Douala au Cameroun"> à me contacter directement.</a></strong></p><h3>MES EXPÉRIENCES PROFESSIONNELLES EN PROGRAMMATION INFORMATIQUE</h3><p>
Afin de mettre en pratique les connaissances acquises lors de ma formation en Programmation Web, <strong>je créa de A à Z et tout seul, un site web(AFRIQUEPLUS)</strong>.  Je dirigeais la conception, le développement et la maintenance du portail internet. Je m\'occupais aussi du référencement, du design,  de l\'accessibilité, de l\'hébergement, de la promotion, du référencement, de la mesure d\'audience,  des mises à jour, bref je m\'occupais de tout.</p><p>
Cette démonstration de mon savoir-faire m\'a permis de travailler comme <strong>Analyste Programmeur Web</strong>, dans plusieurs entreprises camerounaises en l\'instar de Infocomweb (Programmation de leur site web) et de SolidMaison (Sécurisation de leur site web de payement électronique). J\'ai également travaillé comme <strong>Consultant en communication électronique</strong> pour plusieurs agences de communication à l’instar de Ascèse Communication et Oxford Consultech. A cet effet, j\'ai dirigé la Conception, la Réalisation et la Maintenance de nombreux sites web.</p><p> Actuellement, je travaille  à la réalisation d\'un <strong>logiciel professionnel de gestion</strong>, spécialisé dans le secteur de la cablo-distribution. C\'est un excellent moyen pour moi de mettre en pratique les connaissances acquises lors de ma formation en génie logiciel.</p>
<p>&nbsp;&nbsp;<strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas <a href="publications.php#cv_maghen_negou_rostant"  title="CV de MAGHEN NEGOU Rostant, COMMUNICATEUR INFORMATICIEN (10 ans d’expérience)"> à consulter mon CV</a> ou alors <a href="contact.php" title="Contact de MAGHEN NEGOU Rostant, Communicateur et Informaticien à Douala au Cameroun"> à me contacter directement.</a></strong></p><h3>MES EXPÉRIENCES PROFESSIONNELLES EN GESTION D\'ENTREPRISES</h3>
<p>De 2009 à 2010, j\'ai travaillé dans une société de gestion de cybercafé. Tout d\'abord comme <strong>Directeur Commercial</strong> ; mais suite à la survenance répétée d\'incidents techniques, je dus cumuler ce poste avec celui de <strong>Directeur Technique</strong>. Au quatrième trimestre 2009, je racheta deux des points de ventes de l\'entreprise. Ce fut une expérience riche et éprouvante. J\'assurais le <strong>management et la fourniture de service</strong> tel que le webmastering, la maintenance informatique, l\'infographie, le montage vidéo, le callshop, la bureautique, le surf, etc</p><p>La concurrence devenant de plus en plus acerbe dans le secteur des cybercafés, je restructura mon activité pour  inclure les produits vidéoludiques.J\'assurais le <strong>management de deux Cybercafés</strong> doté chacun d\'une capacité  de 22 places.</p>
<p>Actuellement, je me <strong>positionnes sur le marché du web</strong> au Cameroun, d\'où la raison d’être de ce site web. Ce secteur d\'activité est déjà suffisamment mature pour générer dans notre pays d’excellentes opportunités d\'affaire.  </p><p>&nbsp;&nbsp;<strong>Vous êtes intéressés et désirez en savoir plus, n\'hésitez pas <a href="publications.php#cv_maghen_negou_rostant"  title="CV de MAGHEN NEGOU Rostant, COMMUNICATEUR INFORMATICIEN (10 ans d’expérience)"> à consulter mon CV</a> ou alors <a href="contact.php" title="Contact de MAGHEN NEGOU Rostant, Communicateur et Informaticien à Douala au Cameroun"> à me contacter directement.</a></strong></p>'
  );

?>
