<?php
/* Copyrights Mai 213, MAGHEN NEGOU Rostant, Tout droit réservé
MAGHEN NEGOU Rostant
Communicateur Informaticien
Tél:(+237) 77 92 06 85 - 94 27 12 80 - 77 55 57 43 - 77 28 28 51
BP: Douala Cameroun
Email : maghen2@gmail.com
*/
$_article=array(
'title'=>'à propos',
  'keyword'=>'à propos, apropos, à propos de MAGHEN NEGOU Rostant',
  'description'=>'à propos du site web personnel de MAGHEN NEGOU Rostant - Communicateur Informaticien - Webmaster / WebDesigner / Développeur Web en Freelance à Douala au Cameroun',
  'date'=>'général',
  'categorie'=>'2013-04-18 16:44:29',
  'genre'=>'apropos',
  'content'=>'<h1>A PROPOS</h1><h2>A PROPOS DE CE SITE</h2><p>Ce site web répond à un double objectif :</p><ul> <li><strong>Promouvoir ma carrière professionnelle</strong></li> <li><strong>Me positionné sur le marché des services du web au Cameroun</strong></li></ul><p>Pour ce faire, ce site me permettra de publier mes travaux afin de les valorisés. je compte aussi réaliser des tutos sur la programmation informatique afin de <strong>partager avec les autres passionnés du web, des techniques professionnelles</strong>. Je voudrais aussi y présenter mes prestations et références afin de faciliter l\'évolution de ma carrière professionnelle.</p><p>J\'ai réalisé ce site tout seul. Il a été <strong>entièrement codé &laquo;à la main&raquo; dans un profond respect des normes et standards du we</strong>b. Les langages utilisés pour développer ce site sont:<strong> PHP, MySQL, JavaScript, XHTML et CSS</strong>.</p>
<p>J\'estime le trafic initial de mon site à environ 25 visiteurs par jour. Mais j espère attirer progressivement beaucoup de visiteurs en offrant gratuitement des contenus utiles pour l’internaute lambda.</p><h2>A PROPOS DU PROMOTEUR</h2><h3>MON ÉTAT CIVIL</h3><p> Je me nomme <strong>MAGHEN NEGOU Rostant</strong>, citoyen camerounais âgé de 28 ans. <strong>Je suis né et vie à Douala au Cameroun</strong>. J\'ai le privilège d’être marié à une magnifique femme dont le soutien moral à la réalisation de ce projet est incommensurable. Nous avons la garde d\'un charmant enfant. <a href="contact.php" title="Contact de MAGHEN NEGOU Rostant, Communicateur et Informaticien à Douala au Cameroun"> <strong>Pour me contacter, referrez vous à la page de contact</strong></a>.</p><h3>MA PERSONNALITÉ</h3>
<p>La psychologie établit plusieurs types de personnalités, dont le Perfectionnisme. Comme tout perfectionniste, <strong>je retire une réelle sensation de plaisir du travail exigé par un effort soutenu</strong>. Mon entourage pense que je suis quelqu’un qui s\'efforce compulsivement et sans trêve à <strong>atteindre des buts irréalistes et qui ne juge de sa propre valeur qu’en termes de productivité et de performance.</strong> Mes ex-camarades de classe me disaient que je me  comporte comme si <strong>la perfection pouvait et devait être atteinte.</strong></p><p>Je suis d’un caractère plutôt calme et je préfère analyser chaque situation avec lucidité.  J’ai le sens des responsabilités et je suis généralement  considéré comme <strong>quelqu’un de sérieux, qui fait les choses en temps et en heure</strong> ; car pour moi il y’a une place pour chaque chose, et chaque chose à sa place.</p>
<p>Dans mes relations avec les autres, je ne  reconnais pas toujours mes émotions.  Je m’efforce de répondre avec fidélité et générosité aux besoins de mes proches, plutôt par des oeuvres concrètes que par de vaines  paroles. <strong>Je recherche avant tout la paix et la sécurité, mais je sais répondre énergiquement à l’adversité</strong>. Je tiens toujours mes promesses et j’ai tendance à aider les autres sans compter, parfois même au-delà du raisonnable et sans en tirer le moindre avantage.</p><p>Dans mes activités, <strong>je suis respectueux des procédures et des standards car je préfère toujours faire confiance aux  solutions éprouvées</strong>. Je travaille dans un but pratique, aime être plutôt seul et me trouver en position d’autorité. J’ai une bonne mémoire des faits, sais organiser et planifier mon travail et aller jusqu’au bout de mes réalisations</p><h3>MA VIE PROFESSIONNELLE</h3>
<p>J\'offre un service complet qui couvre les domaines du <strong>Marketing</strong>, de la <strong>Communication</strong> et de la <strong>Programmation Informatique.</strong></p><p><strong>10 années d’expérience</strong> professionnelle dans ces domaines m\'ont permis une excellente maîtrise des outils d\'élaboration et d’implémentation de solutions efficaces. Ainsi ma formation pluridisciplinaire répond aux exigences des différents postes que j\'ai eu à occuper dans divers entreprises. Ce ci m\'a amené à me spécialisé en <strong>Communication Marketing Intégrée (CMI).</strong> </p><p>Ma mission est de collaborer avec une variété de clients et une équipe d\'employés motivés et responsables, afin d\'offrir des solutions innovatrices, en ayant toujours en tête l\'obligation de résultats. En effet, Au cours de ma carrière, j\'ai tout particulièrement mis l\'accent sur l\'<strong>amélioration des procédés internes et l\'augmentation du chiffre d\'affaires.</strong> </p>
<p>Comme vous pourrez le constater à la lecture de <strong><a href="publications.php#cv_maghen_negou_rostant" title="CV de MAGHEN NEGOU Rostant (10 ans d’expérience)">mon CV</a></strong>, je suis un habitué des <strong>univers dynamiques et exigeants.</strong> je recherche aujourd’hui de nouveaux défis à relever dans lesquelles je pourrais mettre à profit aussi bien mon expérience que mes qualités relationnelles.</p>
<p><strong>Ma profession est d\'abord pour moi une passion!</strong> Ce qui me fascine tant en Programmation Informatique, c\'est ce <strong>pouvoir de créer à partir de rien ou presque, des programmes intelligents, capables de nous simplifier la tâche,</strong> rendant ainsi la vie plus agréable. <strong>Créer et entretenir une symbiose entre des cibles pourtant si différentes </strong>les unes des autres, n\'est possible que grâce à la magie de la Communication. Parce que produire et vendre ne suffisent pas à être plus efficaces que la concurrence,  le pouvoir du marketing est de <strong>déterminer les besoins et désirs des marchés visés et de produire les satisfactions désirées</strong> de façon rentable.</p><p><strong> <a href="cv.php" title=" La Formation et la Vie Professionelle de MAGHEN NEGOU Rostant, Communicateur et Informaticien à Douala au Cameroun">Vous trouverez les informations détaillées sur mon parcours professionnel en visitant la page consacrée à ce sujet(CV & LM).</a></strong></p>'
  );
?>
